load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "advisorylock",
    srcs = [
        "kvlocktable.go",
        "manager.go",
        "sqltable.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/sql/advisorylock",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/keys",
        "//pkg/kv",
        "//pkg/kv/kvpb",
        "//pkg/roachpb",
        "//pkg/sql/catalog/descpb",
        "//pkg/sql/pgwire/pgcode",
        "//pkg/sql/pgwire/pgerror",
        "//pkg/util/log",
        "//pkg/util/retry",
        "//pkg/util/stop",
        "//pkg/util/uuid",
        "@com_github_cockroachdb_errors//:errors",
    ],
)
